language: go

go:
- 1.13.x

script:
  - make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  file_glob: true
  file: release/*
  on:
    tags: true
