language: go

go:
- 1.13.x

script:
  - make

deploy:
  provider: releases
  skip_cleanup: true
  token:
    secret: c91aa9e41a7d6de1f86b819ba3df2538e0427426
  keep_history: true
  file_glob: true
  file: release/*
  on:
    tags: true
